feat: add code formatting support
FunctionStream/function-stream pull request #65
Opened 2021-06-27 15:11 UTC by yeliulee

2021-06-27 15:18 UTC, RobertIndie requested changes

2021-06-27 15:18 UTC, RobertIndie commented on front-end/README.md
> +# Function-Stream
```suggestion
# Function-Stream front end
```

2021-06-27 15:18 UTC, RobertIndie commented on front-end/README.md
> +install plugin `prettier` (may have been pre-installed in webstorm)
Please use the format like `* Install plugin `prettier` (may have been pre-installed in webstorm)`

2021-06-28 10:51 UTC, RobertIndie approved these changes
LGTM

2021-06-28 12:43 UTC, winnd commented on front-end/.eslintrc.js
>      'no-console': 'off',
Could you please format the whole file, remove all quotes? Since this file has been modified.

2021-06-28 13:05 UTC, winnd approved these changes
Great, LGTM, Thanks for your contribute ;)

2021-06-28 13:07 UTC, merged