Origin/feature gateway
FunctionStream/function-stream pull request #76
Opened 2021-07-09 07:20 UTC by HALOXIAO

init backend

2021-07-09 07:21 UTC, HALOXIAO commented
framework：guice、vert.x

2021-07-11 06:22 UTC, RobertIndie requested changes
I saw a few empty interface classes. Is this PR not yet available for review?

2021-07-11 06:22 UTC, RobertIndie commented on back-end/pom.xml
> +    <groupId>org.function.stream</groupId>
```suggestion
    <groupId>org.functionstream</groupId>
```

2021-07-11 06:22 UTC, RobertIndie commented on back-end/gateway/pom.xml
> +        <groupId>org.function.stream</groupId>
```suggestion
        <groupId>org.functionstream</groupId>
```

2021-07-23 14:52 UTC, RobertIndie requested changes

2021-07-23 14:52 UTC, RobertIndie commented on back-end/gateway/src/main/java/org/functionstream/gateway/common/BusAddressConst.java
> + * @author HALOXIAO
According to 'Code Complete', comments are used to illustrate the purpose of the code. Using it for other purposes like specifying the ownership may result in 'comment decay'.
That said, keeping track of code ownership, change-log and who last modify the file, is the job of a source control tool like git, and should not be inside the comments.

I think we need to add some comments here to Illustrate what this interface is for.

2021-07-23 14:52 UTC, RobertIndie commented on back-end/gateway/pom.xml
> +        <artifactId>functionstream</artifactId>
```suggestion
        <artifactId>gateway</artifactId>
```

2021-07-23 14:52 UTC, RobertIndie commented on back-end/gateway/src/main/java/org/functionstream/gateway/service/ServerService.java
> +public class ServerService {
What is this ServerService class used for?

2021-09-08 12:08 UTC, RobertIndie commented
Is there any update on this PR? @HALOXIAO

2021-09-14 11:49 UTC, HALOXIAO commented
Done

2021-09-22 11:52 UTC, RobertIndie commented
It looks like there are still a lot of comments left to fix. @HALOXIAO

2024-02-03 13:07 UTC, closed without merging